Add AsyncAPI documentation
Devathon-2024-team5/Preguntonic-backend pull request #8
Opened 2024-04-19 16:40 UTC by peenyaa7

## Description

Add a first version of AsyncAPI documentation. Need to be updated in the future

## Trello link:

[Trello card](https://trello.com/c/LY5XgsG8)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2024-04-20 15:51 UTC, JFCowboy commented on docs/asyncapi.yml
> +  title: Example API
```suggestion
  title: Preguntonic API
```

2024-04-20 15:52 UTC, JFCowboy requested changes

2024-04-20 15:52 UTC, JFCowboy commented on docs/asyncapi.yml
> +  title: Example API
```suggestion
  title: Preguntonic API
```

2024-04-22 12:44 UTC, NicolasLLans approved these changes

2024-04-22 13:40 UTC, Gaston-Herrlein approved these changes

2024-04-22 14:48 UTC, JFCowboy approved these changes

2024-04-22 18:35 UTC, merged